[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "llm_orchestrator"
version = "0.0.1"
dependencies = ["llama_cpp", "jsonschema"]

[tool.setuptools.packages.find]
where = ["llm_orchestrator"]
